config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'likes/index'
  post :incoming, to: 'incoming#create'

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks do
     resources :likes, only: [:index, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:show]
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :url, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  validates :title, length: {minimum: 2}, presence: true
  validates :user, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!, except: [:index]

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :get_topic
  before_action :authenticate_user!, except: [:show]

  def show
    @bookmark = @topic.bookmarks.find(params[:id])
  end

  def edit
    @bookmark = @topic.bookmarks.find(params[:id])

  end

  def update
    @bookmark = @topic.bookmarks.find(params[:id])
    authorize @bookmark
    @bookmark.assign_attributes(bookmark_params)

    if @bookmark.save
      flash[:notice] = "Your bookmark was updated"
      redirect_to [@topic, @bookmark]
    else
      render :edit
    end
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @topic.bookmarks.build(bookmark_params)
    @bookmark.user = current_user
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Your bookmark was saved"
      redirect_to [@topic, @bookmark]
    else
      render :new
    end
  end

  def destroy
    @bookmark = @topic.bookmarks.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Your bookmarks was successfully deleted"
      redirect_to topics_path
    else
      flash[:alert] = "There was a problem"
      render :show
    end
  end

  private

  def get_topic
    @topic = Topic.find(params[:topic_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create

    @user = User.find_by(email: params[:sender])
    @topic = Topic.find_by(title: params[:subject])

    @url = params["body-plain"]

    if @user.nil?
      @user = User.new(email: params[:sender], password: "temp0rary_passw0rd")
      @user.skip_confirmation!
      @user.save!
    end

    if @topic.nil?
      @topic = Topic.create!(title: params[:subject], user: @user)
    end

    @bookmark = @topic.bookmarks.create(url: @url)

    head 200
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize like

    if like.save
      flash[:notice] = "You have liked this bookmark"
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:alert] = "There was a problem liking bookmark"
      redirect_to [@bookmark.topic, @bookmark]
    end

  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    authorize like

    if like.destroy
      flash[:notice] = "You have unliked this bookmark"
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:alert] = "There was a problem"
      redirect_to [@bookmark.topic, @bookmark]
    end

  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @topics = Topic.order("title ASC")
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new
    @topic = Topic.create(topic_params)
    @topic.user = current_user

    authorize @topic

    if @topic.save
      flash[:notice] = "Your topic was added"
      redirect_to @topic
    else
      render :new
    end

  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated successfully"
      redirect_to @topic
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic

    if @topic.destroy
      flash[:notice] = "#{@topic.title} was successfully deleted"
      redirect_to topics_path
    else
      flash[:alert] = "There was an error removing topic at this time"
      redirect_to topics_path
    end

  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @bookmarks = Bookmark.where(user: current_user)
    @likes = current_user.likes
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
   css_class = 'form-group'
   css_class << ' has-error' if errors.any?
   content_tag :div, capture(&block), class: css_class
 end
 
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for [topic, bookmark] do |f| %>

<% if bookmark.errors.any? %>
<div class="alert alert-danger">
       <h4><%= pluralize(bookmark.errors.count, "error") %>.</h4>
       <ul>
         <% bookmark.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

<%= form_group_tag(bookmark.errors[:url]) do %>
  <%= f.label :url %>
  <%= f.text_field :url, :class => 'form-control', placeholder: "Enter bookmark url here..." %>
<% end %>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<%= render partial: 'form', locals: {topic: @topic, bookmark: @bookmark} %>

app/views/bookmarks/new.html.erb
<h1>Add Bookmark</h1>

<%= render partial: 'form', locals: {topic: @topic, bookmark: @bookmark} %>

app/views/bookmarks/show.html.erb
<h1>
  <%= @bookmark.url %>
  <% if current_user %>
    <%= render partial: 'likes/like', locals: {bookmark: @bookmark} %>
  <% end %>
</h1>
<% if current_user == @bookmark.user %>
  <p>
    <%= link_to "Edit", edit_topic_bookmark_path %> |
    <%= link_to "Delete", [@bookmark.topic, @bookmark], method: :delete, data: {confirm: "Are you sure you want to delete bookmark"} %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmarks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <div class="container">
    <%= render 'layouts/messages' %>
    <ul class="nav nav-tabs">
      <li class="pull-left"> <%= link_to "Home", root_path, :class => 'navbar-link' %> </li>
      <li class="pull-left"> <%= link_to "Explore", topics_path, :class => 'navbar-link' %> </li>
      <% if user_signed_in? %>
        <li class="pull-right"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <li class="pull-right"> <%= link_to "#{current_user.email}", edit_user_registration_path, :class => 'navbar-link' %> </li>
        <li class="pull-left"> <%= link_to "My Blocmarks", users_show_path, :class => 'navbar-link' %> </li>
      <% else %>
        <li class="pull-right"> <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> </li>
        <li class="pull-right"> <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %> </li>
      <% end %>
    </ul>
  </div>

    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
<div>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
  <% end %>
</div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if topic.errors.any? %>
  <div class="alert alert-danger">
         <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
         <ul>
           <% topic.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
       </div>
     <% end %>

  <%= form_group_tag(topic.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control', placeholder: "Enter new Topic here..." %>
<% end %>

    <%= f.submit "Save", class: "btn btn-success" %>

<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic Title</h1>

<%= render partial: 'form', locals: {topic: @topic} %>

app/views/topics/index.html.erb
<h1>Explore Topics</h1>

<% if current_user %>
  <p> <%= link_to "Add Topic", new_topic_path %> </p>
<% end %>

<% @topics.each do |topic| %>
<div class="topic-list">
  <h2> <%= link_to "##{topic.title}", topic %> </h2>
  <% topic.bookmarks.first(4).each do |mark| %>
    <div class="marks">
      <%= link_to "#{mark.url}", topic_bookmark_url(topic, mark), :class => 'linked-text' %>
      <% if current_user %>
        <%= render partial: 'likes/like', locals: {bookmark: mark} %>
      <% end %>
    </div>
  <% end %>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>Add a New Topic</h1>

<%= render partial: 'form', locals: {topic: @topic} %>

app/views/topics/show.html.erb
<h1> <%= "#" + @topic.title %>
<%= link_to "Add Bookmark", new_topic_bookmark_path(@topic), :class => 'btn btn-default view-button' %>
</h1>
<% if current_user == @topic.user %>
  <p>
     <%= link_to "Edit", edit_topic_path %> |
     <%= link_to "Remove", @topic, method: :delete, data: {confirm: "Are you sure you want to remove topic?  All bookmarks in topic will be removed as well"} %>
  </p>
  <% end %>

<% if @topic.bookmarks.count > 0 %>
  <% @topic.bookmarks.each do |mark| %>
    <div class="marks">
      <%= mark.url %>
      <div>
        <%= link_to "View", topic_bookmark_url(@topic, mark), :class => 'btn btn-default view-button' %>
        <% if current_user %>
          <%= render partial: 'likes/like', locals: {bookmark: mark} %>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <p> No bookmarks for this topic! </p>
<% end %>

app/views/users/show.html.erb
<h1>My Blocmarks</h1>
<% @bookmarks.each do |mark| %>
  <h2> <%= link_to "##{mark.topic.title}", mark.topic %> </h2>
  <div class="marks">
    <%= link_to "#{mark.url}", topic_bookmark_url(mark.topic, mark), :class => 'linked-text' %>
  </div>

<% end %>

<h1>Liked Blocmarks</h1>
<% @likes.each do |like| %>
  <div class="marks">
    <%= link_to "#{like.bookmark.url}", topic_bookmark_url(like.bookmark.topic, like.bookmark), :class => 'linked-text' %>
    <% if current_user %>
      <%= render partial: 'likes/like', locals: {bookmark: like.bookmark} %>
    <% end %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>BlocMarks</h1>
</div>
<p>Save Share & Organize Book Marks</p>